import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth-v5'
import { getSubscription } from '@/lib/subscription/subscriptionEngine'
import type { PlanId } from '@/lib/subscription/catalog'
import { z } from 'zod'
import { logger } from '@/lib/logger'

// AUTO-GENERATED by api-row-sweep --apply — REVIEW these column types.
// pg returns bigint/numeric as string, timestamptz as Date; add `| null` where nullable.
interface UserSubscriptionRow {
  id: string
}

export const dynamic = 'force-dynamic'

// ─── Zod Schemas ──────────────────────────────────────────────────────────────

const SubscriptionActionSchema = z.object({
  planId: z.string(),
  action: z.enum(['subscribe', 'cancel', 'upgrade']),
})

/**
 * GET /api/subscription
 *
 * Returns the current user's subscription info.
 * Uses the server-side subscriptionEngine which correctly
 * detects admin emails and grants enterprise access.
 *
 * This replaces direct client-side DB reads of user_subscriptions
 * which missed the admin bypass logic.
 */
export async function GET() {
  try {
    const session = await auth()
    if (!session?.user?.id) {
      return NextResponse.json({ plan: 'free', status: 'active' }, { status: 401 })
    }

    const userId = session.user.id
    const email = session.user.email ?? undefined

    const sub = await getSubscription(userId, email)

    if (!sub) {
      // No subscription row — default to free tier (admin check already done inside getSubscription)
      return NextResponse.json({
        plan: 'free' as PlanId,
        status: 'active',
        isUnlimitedProjects: false,
        isUnlimitedPoints: false,
        maxTeamMembers: 1,
        isAdmin: false,
      })
    }

    return NextResponse.json({
      plan: sub.plan,
      status: sub.status,
      trialEndsAt: sub.trialEndsAt,
      periodStart: sub.periodStart,
      periodEnd: sub.periodEnd,
      paymentMethod: sub.paymentMethod,
      currency: sub.currency,
      isUnlimitedProjects: sub.isUnlimitedProjects,
      isUnlimitedPoints: sub.isUnlimitedPoints,
      maxTeamMembers: sub.maxTeamMembers,
      isAdmin: sub.paymentMethod === 'admin',
    })
  } catch (error) {
    logger.error('[/api/subscription] Error:', { error: error })
    return NextResponse.json({ plan: 'free', status: 'active' }, { status: 500 })
  }
}

/**
 * POST /api/subscription
 *
 * Subscribe, cancel, or upgrade a subscription plan.
 */
export async function POST(request: NextRequest) {
  try {
    const session = await auth()
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Authentication required', code: 'UNAUTHORIZED' }, { status: 401 })
    }

    const rawBody: unknown = await request.json()
    const parsed = SubscriptionActionSchema.safeParse(rawBody)
    if (!parsed.success) {
      return NextResponse.json({ error: 'Validation failed', details: parsed.error.issues }, { status: 400 })
    }

    const { planId, action } = parsed.data
    const userId = session.user.id

    // Import db dynamically to avoid circular deps
    const { db } = await import('@/lib/db')

    if (action === 'subscribe') {
      // Check for existing active subscription
      const { rows: existing } = await db.query<UserSubscriptionRow>(
        'SELECT id FROM user_subscriptions WHERE user_id = $1 AND status = $2',
        [userId, 'active']
      )

      if (existing.length > 0) {
        return NextResponse.json(
          { error: 'You already have an active subscription. Use upgrade to change plans.', code: 'EXISTING_SUBSCRIPTION' },
          { status: 409 }
        )
      }

      // Create new subscription
      const trialEndsAt = new Date(Date.now() + 14 * 24 * 60 * 60 * 1000) // 14-day trial
      await db.query<never>(
        `INSERT INTO user_subscriptions (user_id, plan_id, status, trial_ends_at, current_period_start, current_period_end)
         VALUES ($1, $2, 'active', $3, NOW(), NOW() + INTERVAL '30 days')`,
        [userId, planId, trialEndsAt.toISOString()]
      )

      return NextResponse.json({ success: true, planId, action: 'subscribe', trialEndsAt: trialEndsAt.toISOString() })
    }

    if (action === 'cancel') {
      await db.query<never>(
        `UPDATE user_subscriptions SET status = 'cancelled', cancelled_at = NOW() WHERE user_id = $1 AND status = 'active'`,
        [userId]
      )

      return NextResponse.json({ success: true, planId, action: 'cancel' })
    }

    if (action === 'upgrade') {
      await db.query<never>(
        `UPDATE user_subscriptions SET plan_id = $1, upgraded_at = NOW() WHERE user_id = $2 AND status = 'active'`,
        [planId, userId]
      )

      return NextResponse.json({ success: true, planId, action: 'upgrade' })
    }

    return NextResponse.json({ error: 'Unknown action' }, { status: 400 })
  } catch (error) {
    logger.error('[/api/subscription POST] Error:', { error: error })
    return NextResponse.json({ error: 'Subscription action failed' }, { status: 500 })
  }
}
