export const dynamic = 'force-dynamic'

import { NextResponse } from 'next/server'
import { z } from 'zod'
import { apiHandler } from '@/lib/apiHandler'
import { db, setRlsContext } from '@/lib/db'
import { SaveStationsSchema } from '@/lib/validation/apiSchemas'

// AUTO-GENERATED by api-row-sweep --apply — REVIEW these column types.
// pg returns bigint/numeric as string, timestamptz as Date; add `| null` where nullable.
interface SETRow {
  alignment_id: string
  chainage: string
  ground_level: string
}

// POST: Save cross-section station data (bulk upsert)
interface AlignmentStationRow {
  id: string
  alignment_id: string
  chainage: number | null
  station_name: string | null
  easting: number | null
  northing: number | null
  elevation: number | null
}


export const POST = apiHandler({ auth: true, schema: SaveStationsSchema, rateLimit: { max: 60, windowMs: 60000 } }, async (req, ctx) => {
  const { alignment_id, stations } = ctx.body as z.infer<typeof SaveStationsSchema>

  const client = await db.getClient()

  try {
    await client.query<never>('BEGIN')
    // Set RLS context for this client — CRITICAL for row-level security
    await setRlsContext(client)

    const insertedRows: SETRow[] = []
    for (const station of stations) {
      const { rows } = await client.query<SETRow>(
        `INSERT INTO alignment_stations (alignment_id, chainage, ground_level)
         VALUES ($1, $2, $3)
         ON CONFLICT (alignment_id, chainage) DO UPDATE SET
          ground_level = EXCLUDED.ground_level,
          updated_at = NOW()
         RETURNING *`,
        [alignment_id, station.chainage, station.ground_level]
      )
      insertedRows.push(rows[0])
    }

    await client.query<never>('COMMIT')

    return NextResponse.json({ data: insertedRows })
  } catch (txErr) {
    await client.query<never>('ROLLBACK')
    throw txErr
  } finally {
    client.release()
  }
})

// GET: Retrieve stations for an alignment
export const GET = apiHandler({ auth: true, rateLimit: { max: 60, windowMs: 60000 } }, async (req, _ctx) => {
  const { searchParams } = new URL(req.url)
  const alignmentId = searchParams.get('alignment_id')

  if (!alignmentId) {
    return NextResponse.json({ error: 'Missing alignment_id query parameter' }, { status: 400 })
  }

  const { rows } = await db.query<AlignmentStationRow>(
    'SELECT * FROM alignment_stations WHERE alignment_id = $1 ORDER BY chainage ASC',
    [alignmentId]
  )

  return NextResponse.json({ data: rows })
})
