import { NextResponse } from 'next/server'
import { apiHandler } from '@/lib/apiHandler'
import { db } from '@/lib/db'

// AUTO-GENERATED by api-row-sweep --apply — column types from migrations/*.sql + name heuristics.
// pg returns bigint/numeric as string, timestamptz as Date; nullable columns carry `| null`; REVIEW.
interface EquipmentRow {
  last_calibration_date: Date | null
  interval_days: number | null
}
export const dynamic = 'force-dynamic'

export const GET = apiHandler({ auth: true, rateLimit: { max: 60, windowMs: 60000 } }, async (req, ctx) => {
  const result = await db.query<EquipmentRow>(
    `SELECT last_calibration_date, interval_days FROM equipment WHERE user_id = $1`,
    [ctx.userId]
  )

  if (!result.rows.length) {
    return NextResponse.json({ count: 0 })
  }

  const today = new Date()
  const overdue = result.rows.filter((eq) => {
    const last = eq.last_calibration_date
    if (!last) return false
    const nextCal = new Date(last.getTime() + (eq.interval_days ?? 365) * 86400000)
    return nextCal < today
  }).length

  return NextResponse.json({ count: overdue })
})
