export const dynamic = 'force-dynamic'

import { NextResponse } from 'next/server'
import { z } from 'zod'
import { apiHandler } from '@/lib/apiHandler'
import { db } from '@/lib/db'
import { callPythonCompute } from '@/lib/compute/pythonService'
import { ProcessGNSSSchema } from '@/lib/validation/apiSchemas'

// AUTO-GENERATED by api-row-sweep --apply — column types from migrations/*.sql + name heuristics.
// pg returns bigint/numeric as string, timestamptz as Date; nullable columns carry `| null`; REVIEW.
interface GnssSessionRow {
  id: string
}

export const POST = apiHandler({ auth: true, schema: ProcessGNSSSchema, rateLimit: { max: 60, windowMs: 60000 } }, async (request, ctx) => {
  const { projectId, files, stationLabels } = ctx.body as z.infer<typeof ProcessGNSSSchema>

  // Create session record
  const sessionRes = await db.query<GnssSessionRow>(
    `INSERT INTO gnss_sessions (
      project_id, user_id, status, input_files
    ) VALUES ($1, $2, $3, $4)
    RETURNING id`,
    [projectId, ctx.userId, 'processing', JSON.stringify(files)]
  )
  const gnssSessionId = sessionRes.rows[0].id

  // Call Python service for processing
  const result = await callPythonCompute<{ baselines?: Record<string, unknown>[] }>('/gnss/process', {
    files,
    stationLabels
  })

  let results: Record<string, unknown>[] = []
  let status: 'complete' | 'failed' | 'simulated' = 'complete'
  let errorMsg: string | undefined

  if (result.ok) {
    results = result.value?.baselines || []
  } else if ((result as { ok: false; fallback?: boolean }).fallback) {
    // Simulation mode - generate mock results
    status = 'simulated'
    results = generateMockBaselines(stationLabels ?? [])
    errorMsg = (result as { error: string }).error
  } else {
    status = 'failed'
    errorMsg = (result as { error: string }).error
  }

  // Update session with results
  await db.query<never>(
    `UPDATE gnss_sessions SET
      status = $1,
      results = $2,
      error_msg = $3,
      updated_at = $4
    WHERE id = $5`,
    [
      results.length > 0 ? 'complete' : 'failed',
      JSON.stringify(results),
      errorMsg,
      new Date().toISOString(),
      gnssSessionId
    ]
  )

  return NextResponse.json({
    sessionId: gnssSessionId,
    results,
    status,
    message: status === 'simulated' ? 'Simulation mode — upload valid RINEX for real processing' : undefined
  })
})

function generateMockBaselines(_stationLabels: string[]): Record<string, unknown>[] {
  // No fabricated baseline data — return empty result
  return []
}
