export const dynamic = 'force-dynamic'

import { NextResponse } from 'next/server'
import { z } from 'zod'
import { apiHandler } from '@/lib/apiHandler'
import { db } from '@/lib/db'
import { callPythonCompute } from '@/lib/compute/pythonService'

// AUTO-GENERATED by api-row-sweep --apply — column types from migrations/*.sql + name heuristics.
// pg returns bigint/numeric as string, timestamptz as Date; nullable columns carry `| null`; REVIEW.
interface GnssSessionRow {
  id: string
}

/**
 * POST /api/gnss/process — multi-station RINEX processing (differential SPP).
 *
 * REVIVED 2026-08-31 (audit C9 "make it work"): the form previously uploaded
 * file METADATA only (filename/size) — no content ever reached a processor,
 * so every submission was guaranteed to produce nothing. Files are now read
 * in the browser, sent as base64, and processed by the worker's real SPP
 * engine (python_worker/gnss_processor.py): per-station code positions and
 * pairwise station-to-station baselines.
 *
 * Honesty: baselines are metre-level differential SPP (common ephemeris
 * errors only partially cancel). The RTKLIB baseline processor
 * (/api/gnss/baseline-process) remains the survey-grade path.
 */

const ProcessGNSSSchema = z.object({
  projectId: z.string().min(1, 'projectId is required'),
  files: z.array(z.object({
    filename: z.string().min(1).max(255),
    stationId: z.string().max(50).optional(),
    stationLabel: z.string().max(50).optional(),
    fileType: z.enum(['OBS', 'NAV']).optional(),
    sizeBytes: z.number().int().nonnegative().optional(),
    storagePath: z.string().max(500).optional(),
    content: z.string().min(1, 'file content (base64) is required for processing'),
  })).min(2, 'Need at least 2 files (one observation file + one navigation file, or two observation files)'),
  stationLabels: z.array(z.string().max(50)).optional(),
  usePreciseEphemeris: z.boolean().optional(),
})

interface StationResult {
  station: string
  ok: boolean
  error?: string
  latitude?: number
  longitude?: number
  height?: number
  ecef?: number[]
  sigma_m?: { east: number; north: number; up: number }
  method?: string
  n_satellites?: number
  n_epochs?: number
  rms?: number
  warnings?: string[]
}

interface WorkerBaseline {
  from: string
  to: string
  delta_x_m: number
  delta_y_m: number
  delta_z_m: number
  delta_e_m: number
  delta_n_m: number
  delta_u_m: number
  distance_m: number
  sigma_m: number
  method: string
  note: string
}

export const POST = apiHandler(
  { auth: true, schema: ProcessGNSSSchema, rateLimit: { max: 5, windowMs: 60000 } },
  async (request, ctx) => {
    const { projectId, files, usePreciseEphemeris } = ctx.body as z.infer<typeof ProcessGNSSSchema>

    const withContent = files.filter(f => f.content)
    if (withContent.length === 0) {
      return NextResponse.json(
        { error: 'No file content received — re-upload the RINEX files and retry.' },
        { status: 400 },
      )
    }

    // Session record (audit trail of what was processed)
    const sessionRes = await db.query<GnssSessionRow>(
      `INSERT INTO gnss_sessions (
        project_id, user_id, status, input_files
      ) VALUES ($1, $2, $3, $4)
      RETURNING id`,
      [projectId, ctx.userId, 'processing',
       JSON.stringify(files.map(({ content, ...meta }) => ({ ...meta, contentBytes: content.length })))]
    )
    const gnssSessionId = sessionRes.rows[0].id

    const result = await callPythonCompute<{
      stations?: StationResult[]
      baselines?: WorkerBaseline[]
      notes?: string[]
    }>('gnss_process_rinex_multi', {
      files: files.map(f => ({
        filename: f.filename,
        stationId: f.stationId || f.stationLabel || f.filename,
        fileType: f.fileType || (/\.(nav|n|rnx)$/i.test(f.filename) && !/\d[od]$/.test(f.filename) ? 'NAV' : 'OBS'),
        content: f.content,
      })),
      use_precise_ephemeris: usePreciseEphemeris ?? false,
    }, { timeoutMs: 300_000 })

    if (!result.ok) {
      await db.query<never>(
        `UPDATE gnss_sessions SET status = $1, error_msg = $2, updated_at = $3 WHERE id = $4`,
        ['failed', result.error, new Date().toISOString(), gnssSessionId]
      )
      return NextResponse.json(
        { sessionId: gnssSessionId, results: [], status: 'failed', error: result.error },
        { status: result.status },
      )
    }

    const stations = result.value?.stations ?? []
    const baselines = result.value?.baselines ?? []
    const failed = stations.filter(s => !s.ok)

    await db.query<never>(
      `UPDATE gnss_sessions SET
        status = $1,
        results = $2,
        error_msg = $3,
        updated_at = $4
      WHERE id = $5`,
      [
        failed.length === stations.length ? 'failed' : 'complete',
        JSON.stringify({ stations, baselines }),
        failed.length ? `${failed.length} station(s) failed: ${failed.map(f => f.station).join(', ')}` : null,
        new Date().toISOString(),
        gnssSessionId,
      ]
    )

    return NextResponse.json({
      sessionId: gnssSessionId,
      results: baselines,
      stations,
      status: failed.length === stations.length ? 'failed' : 'complete',
      notes: result.value?.notes ?? [],
    })
  }
)
