export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { logger } from '@/lib/logger'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { sendTemplatedEmail } from '@/lib/email-templates'
import { db } from '@/lib/db'

// AUTO-GENERATED by api-row-sweep --apply — column types from migrations/*.sql + name heuristics.
// pg returns bigint/numeric as string, timestamptz as Date; nullable columns carry `| null`; REVIEW.
interface UserSubscriptionRow {
  id: string
}
export async function POST(_req: NextRequest) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const existingSub = await db.query<UserSubscriptionRow>(
    'SELECT id FROM user_subscriptions WHERE user_id = $1',
    [session.user.id]
  )

  if (existingSub.rows.length > 0) {
    return NextResponse.json({ ok: true })
  }

  const now = new Date()
  await db.query<never>(
    `INSERT INTO user_subscriptions 
     (user_id, plan_id, status, trial_ends_at, current_period_start, current_period_end)
     VALUES ($1, 'pro', 'trial', $2, $3, $4)`,
    [
      session.user.id,
      new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      now.toISOString(),
      new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString()
    ]
  )

  // Fire-and-forget welcome email — don't block the response. Sent directly
  // through the template registry (the previous self-HTTP fetch carried no
  // session cookie, so /api/emails/welcome always 401'd and the email never
  // fired), and with the REAL trial end date we just persisted.
  const userEmail = session.user.email
  const userName = session.user.name
  if (userEmail) {
    void sendTemplatedEmail('welcome', {
      to: userEmail,
      name: userName || '',
      trialEndsAt: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    }).then((res) => {
      if (!res.success && res.error !== 'Email service not configured') {
        logger.warn('[register-complete] Welcome email not sent:', { error: res.error })
      }
    })
  }

  return NextResponse.json({ ok: true })
}
