export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { logger } from '@/lib/logger'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { db } from '@/lib/db'

// AUTO-GENERATED by api-row-sweep --apply — column types from migrations/*.sql + name heuristics.
// pg returns bigint/numeric as string, timestamptz as Date; nullable columns carry `| null`; REVIEW.
interface UserSubscriptionRow {
  id: string
}
export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const existingSub = await db.query<UserSubscriptionRow>(
    'SELECT id FROM user_subscriptions WHERE user_id = $1',
    [session.user.id]
  )

  if (existingSub.rows.length > 0) {
    return NextResponse.json({ ok: true })
  }

  const now = new Date()
  await db.query<never>(
    `INSERT INTO user_subscriptions 
     (user_id, plan_id, status, trial_ends_at, current_period_start, current_period_end)
     VALUES ($1, 'pro', 'trial', $2, $3, $4)`,
    [
      session.user.id,
      new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      now.toISOString(),
      new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString()
    ]
  )

  // Fire-and-forget welcome email — don't block the response
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://metardu.space'
  const userEmail = session.user.email
  const userName = session.user.name
  if (userEmail) {
    fetch(`${baseUrl}/api/emails/welcome`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: userEmail, name: userName || '' })
    }).catch((err: unknown) => logger.warn('[register-complete] Welcome email failed:', { error: err instanceof Error ? err.message : String(err) }))
  }

  return NextResponse.json({ ok: true })
}
