import { NextResponse } from 'next/server'
import { apiHandler } from '@/lib/apiHandler'
import { db } from '@/lib/db'

// AUTO-GENERATED by api-row-sweep --apply — column types from migrations/*.sql + name heuristics.
// pg returns bigint/numeric as string, timestamptz as Date; nullable columns carry `| null`; REVIEW.
interface EquipmentRow {
  id: string
  user_id: string | null
  name: string
  type: string
  manufacturer: string | null
  model: string | null
  serial_number: string | null
  purchase_date: Date | null
  purchase_cost: string | null
  status: string | null
  notes: string | null
  created_at: Date
  updated_at: Date
}
export const dynamic = 'force-dynamic'

export const GET = apiHandler({ auth: true, rateLimit: { max: 60, windowMs: 60000 } }, async (req, ctx) => {
  const result = await db.query<EquipmentRow>(
    'SELECT * FROM equipment WHERE user_id = $1 ORDER BY created_at DESC',
    [ctx.userId]
  )

  const formatted = (result.rows || []).map((eq) => ({
    id: eq.id,
    userId: eq.user_id,
    name: eq.name,
    type: eq.type,
    make: eq.manufacturer,
    model: eq.model,
    serialNumber: eq.serial_number,
    purchaseDate: eq.purchase_date,
    status: eq.status,
    notes: eq.notes,
    calibrationHistory: []
  }))

  return NextResponse.json({ equipment: formatted })
})
