#!/usr/bin/env node
/**
 * Mobile Build (Capacitor static export)
 * ======================================
 *
 * The Capacitor app ("METARDU Access") is a static export (`output: 'export'`)
 * that talks to the REMOTE METARDU server over HTTP (CapacitorHttp). It does
 * not need the Next.js API routes at all — and Next.js 14 rejects any route
 * handler with `export const dynamic = 'force-dynamic'` under `output: 'export'`.
 *
 * It also does not need the *dynamic web routes* (`/project/[id]/...`,
 * `/survey/[id]/...`, `/guide/[type]`, `/verify/[token]`): under
 * `output: 'export'` every dynamic route must be pre-generated by
 * `generateStaticParams()`, and those pages are backed by the server-side
 * database (which cannot run at build time in CI). They are web-admin pages,
 * not part of the mobile field app — so they are stashed from the export too.
 *
 * This script temporarily moves those directories outside the app directory,
 * runs the static export build, and restores everything afterwards (even on
 * failure, via a finally block).
 *
 * Usage:  node scripts/mobile-build.mjs
 * Env:    MOBILE_BUILD=true is set automatically.
 */

import { execSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const APP_DIR = path.join(ROOT, 'src', 'app')
const STASH_DIR = path.join(ROOT, 'src', '.stash-mobile-build')

// Directories that must NOT be part of the static export:
// - src/app/api                    -> API routes (remote server does this)
// - dynamic web routes             -> need server-side DB at build time
// - server-backed pages            -> read searchParams/request/cookies/db at
//                                      render time; cannot be statically
//                                      exported (deed-plan, working-diagram,
//                                      audit-logs, auth/callback, etc.)
// - import/share-target            -> POST route handler outside api/
const STASH_SUBTREES = [
  'api',
  '(dashboard)/survey/[id]',
  'guide/[type]',
  'project/[id]',
  'verify/[token]',
  'import/share-target',
  'auth/callback',
  'audit-logs',
  'deed-plan',
  'working-diagram',
  'subscription/success',
  'dashboard',
  'settings/profile',
  // opengraph-image (metadata route): `next/og`'s ImageResponse WASM cannot
  // run during static export prerender (web-only social sharing preview).
  'opengraph-image.tsx',
]

function run(cmd) {
  console.log(`$ ${cmd}`)
  execSync(cmd, {
    cwd: ROOT,
    stdio: 'inherit',
    shell: true,
    // Pass env vars programmatically — POSIX-style `VAR=x cmd` prefixes are
    // not supported by cmd.exe on Windows.
    env: {
      ...process.env,
      MOBILE_BUILD: 'true',
      NEXT_PUBLIC_SENTRY_DSN: '',
      DISABLE_PWA: 'true',
    },
  })
}

// Collect the actual paths to move (they must exist). The stash keeps the
// full relative structure so distinct dirs with the same basename (e.g.
// `project/[id]` and `(dashboard)/survey/[id]`) never collide.
const toMove = STASH_SUBTREES
  .map((rel) => ({ rel, abs: path.join(APP_DIR, rel) }))
  .filter(({ abs }) => fs.existsSync(abs))

if (toMove.length === 0) {
  console.log('Nothing to stash — running a plain static export build.')
}

const moved = []

try {
  // Remove any stale stash from a previous interrupted run
  if (fs.existsSync(STASH_DIR)) fs.rmSync(STASH_DIR, { recursive: true, force: true })

  for (const { rel, abs } of toMove) {
    const dest = path.join(STASH_DIR, rel)
    fs.mkdirSync(path.dirname(dest), { recursive: true })
    console.log(`→ Stashing ${path.relative(ROOT, abs)}`)
    fs.renameSync(abs, dest)
    moved.push({ abs, dest })
  }

  run('npx next build')
  console.log('✓ Mobile static export build succeeded')
} finally {
  for (const { abs, dest } of moved.reverse()) {
    console.log(`→ Restoring ${path.relative(ROOT, abs)}`)
    if (fs.existsSync(abs)) fs.rmSync(abs, { recursive: true, force: true })
    fs.mkdirSync(path.dirname(abs), { recursive: true })
    fs.renameSync(dest, abs)
  }
  // Clean up the empty stash container
  if (fs.existsSync(STASH_DIR)) {
    fs.rmSync(STASH_DIR, { recursive: true, force: true })
  }
}
