/**
 * Graphify to Obsidian Vault Exporter
 * Converts graphify-out/graph.json into an interlinked Obsidian Vault knowledge base.
 */

import * as fs from 'fs'
import * as path from 'path'

interface GraphNode {
  id: string
  label: string
  source_file?: string
  source_location?: string
  community?: number
  degree?: number
  file_type?: string
}

interface GraphLink {
  source: string | number
  target: string | number
  relation?: string
  confidence?: 'EXTRACTED' | 'INFERRED' | string
}

interface GraphData {
  nodes: GraphNode[]
  links?: GraphLink[]
  edges?: GraphLink[]
}

export function syncGraphToObsidian(vaultPath?: string) {
  const graphJsonPath = path.join(__dirname, '../graphify-out/graph.json')
  if (!fs.existsSync(graphJsonPath)) {
    console.error('graph.json not found in graphify-out. Run graphify first.')
    return
  }

  const targetDir = vaultPath || path.join(__dirname, '../graphify-out/obsidian-vault')
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true })
  }

  console.log('Reading graph.json...')
  const raw = fs.readFileSync(graphJsonPath, 'utf-8')
  const graph: GraphData = JSON.parse(raw)
  const links = graph.links || graph.edges || []

  console.log(`Processing ${graph.nodes.length} nodes and ${links.length} relationships...`)

  // Index edges by node ID
  const outgoing = new Map<string, Array<{ target: string; type: string; confidence: string }>>()
  const incoming = new Map<string, Array<{ source: string; type: string; confidence: string }>>()
  const degreeMap = new Map<string, number>()

  for (const link of links) {
    const s = String(link.source)
    const t = String(link.target)
    const rel = link.relation || 'references'
    const conf = link.confidence || 'EXTRACTED'

    degreeMap.set(s, (degreeMap.get(s) || 0) + 1)
    degreeMap.set(t, (degreeMap.get(t) || 0) + 1)

    if (!outgoing.has(s)) outgoing.set(s, [])
    outgoing.get(s)!.push({ target: t, type: rel, confidence: conf })

    if (!incoming.has(t)) incoming.set(t, [])
    incoming.get(t)!.push({ source: s, type: rel, confidence: conf })
  }

  // Create an index file
  let indexMd = `# METARDU Architecture Knowledge Base (Graphify ↔ Obsidian)\n\n`
  indexMd += `> Generated by Graphify AST Parser on ${new Date().toISOString().split('T')[0]}\n\n`
  indexMd += `- **Total Codebase Nodes**: \`${graph.nodes.length}\`\n`
  indexMd += `- **Total Architectural Relationships**: \`${links.length}\`\n\n`
  indexMd += `## Top 50 Architectural God Nodes\n\n`

  // Sort nodes by degree
  const sortedNodes = [...graph.nodes].sort((a, b) => (degreeMap.get(b.id) || 0) - (degreeMap.get(a.id) || 0))
  const topNodes = sortedNodes.slice(0, 50)

  for (const node of topNodes) {
    const degree = degreeMap.get(node.id) || 0
    const cleanId = node.id.replace(/[^a-zA-Z0-9_-]/g, '_')
    indexMd += `- [[${cleanId}|${node.label}]] (${degree} connections) — \`${node.source_file || 'global'}\`\n`
  }

  fs.writeFileSync(path.join(targetDir, '00_METARDU_ARCHITECTURE_INDEX.md'), indexMd)

  // Write top nodes as Markdown notes with [[Wikilinks]]
  for (const node of topNodes) {
    const cleanId = node.id.replace(/[^a-zA-Z0-9_-]/g, '_')
    const degree = degreeMap.get(node.id) || 0

    let nodeMd = `# ${node.label}\n\n`
    nodeMd += `- **Source File**: \`${node.source_file || 'N/A'}:${node.source_location || 'L1'}\`\n`
    nodeMd += `- **Community**: \`#community_${node.community ?? 0}\`\n`
    nodeMd += `- **Connections (Degree)**: ${degree}\n\n`

    const outList = outgoing.get(node.id) || []
    if (outList.length > 0) {
      nodeMd += `## Outgoing Dependencies & Calls\n`
      for (const e of outList.slice(0, 25)) {
        const targetClean = e.target.replace(/[^a-zA-Z0-9_-]/g, '_')
        nodeMd += `- [[${targetClean}|${e.target}]] — *${e.type}* (${e.confidence})\n`
      }
      nodeMd += `\n`
    }

    const inList = incoming.get(node.id) || []
    if (inList.length > 0) {
      nodeMd += `## Incoming References\n`
      for (const e of inList.slice(0, 25)) {
        const sourceClean = e.source.replace(/[^a-zA-Z0-9_-]/g, '_')
        nodeMd += `- [[${sourceClean}|${e.source}]] — *${e.type}* (${e.confidence})\n`
      }
      nodeMd += `\n`
    }

    fs.writeFileSync(path.join(targetDir, `${cleanId}.md`), nodeMd)
  }

  console.log(`Obsidian Vault markdown knowledge base successfully exported to: ${targetDir}`)
}

if (require.main === module) {
  syncGraphToObsidian()
}
