export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { apiHandler } from '@/lib/apiHandler'
import { db } from '@/lib/db'
import { requireProjectOwnership } from '@/lib/auth/ownership'

// AUTO-GENERATED by api-row-sweep --apply — column types from migrations/*.sql + name heuristics.
// pg returns bigint/numeric as string, timestamptz as Date; nullable columns carry `| null`; REVIEW.
interface ProjectFieldbookEntryRow {
  id: string
  project_id: string
  row_index: number
  station: string | null
  bearing: number | null
  distance: number | null
  raw_data: unknown | null
  import_session_id: string | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
  deleted_by: string | null
  signed_audit: unknown | null
}

export const GET = apiHandler({ auth: true, rateLimit: { max: 60, windowMs: 60000 } }, async (req, ctx) => {
  const { id } = ctx.params

  // IDOR protection — verify project ownership
  const ownership = await requireProjectOwnership(id, ctx.userId)
  if (!ownership.ok) return ownership.error!

  const { rows } = await db.query<ProjectFieldbookEntryRow>(
    `SELECT * FROM project_fieldbook_entries
     WHERE project_id = $1
     ORDER BY row_index ASC`,
    [id]
  )

  return NextResponse.json({ data: rows })
})
