export const dynamic = 'force-dynamic'

/**
 * POST /api/submission/sequence
 * Atomically increments the submission sequence number for a surveyor/year pair.
 * Uses direct PostgreSQL with advisory lock instead of DbClient RPC.
 */

import { NextResponse } from 'next/server'
import { apiHandler } from '@/lib/apiHandler'
import { db } from '@/lib/db'

// AUTO-GENERATED by api-row-sweep --apply — column types from migrations/*.sql + name heuristics.
// pg returns bigint/numeric as string, timestamptz as Date; nullable columns carry `| null`; REVIEW.
interface SubmissionSequenceRow {
  seq: number
}
export const POST = apiHandler({ auth: true, rateLimit: { max: 60, windowMs: 60000 } }, async (req, ctx) => {
  const body = ctx.body as { surveyorProfileId?: string; year?: number } | null

  if (!body?.surveyorProfileId || !body.year) {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 })
  }

  const { surveyorProfileId, year } = body

  // Canonical atomic sequence increment (migration 047). Replaces the old
  // INSERT INTO submission_sequences (plural) upsert — folded into the
  // submission_sequence table in migration 048.
  const { rows } = await db.query<SubmissionSequenceRow>(
    `SELECT increment_submission_sequence($1, $2) AS seq`,
    [surveyorProfileId, year]
  )

  const sequence = rows[0]?.seq ?? 1
  const referenceNumber = `ISK_${year}_${String(sequence).padStart(3, '0')}_R00`

  return NextResponse.json({
    sequence,
    reference_number: referenceNumber,
    revision: 0,
    year
  })
})
